"""Add google_id to User model

Revision ID: acd5bddc3168
Revises: 20260503_debt_type
Create Date: 2026-05-12 11:13:18.046214

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'acd5bddc3168'
down_revision = '20260503_debt_type'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('google_id', sa.String(length=50), nullable=True))
        batch_op.alter_column('telegram_id',
               existing_type=sa.BIGINT(),
               nullable=True)
        batch_op.create_unique_constraint(None, ['google_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('telegram_id',
               existing_type=sa.BIGINT(),
               nullable=False)
        batch_op.drop_column('google_id')

    # ### end Alembic commands ###
