"""Add Google OAuth fields to User model

Revision ID: e49a6c3dc4b8
Revises: acd5bddc3168
Create Date: 2026-05-12 11:25:07.345419

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e49a6c3dc4b8'
down_revision = 'acd5bddc3168'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('avatar_url', sa.String(length=255), nullable=True))
        batch_op.alter_column('telegram_id',
               existing_type=sa.BIGINT(),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.alter_column('telegram_id',
               existing_type=sa.BIGINT(),
               nullable=True)
        batch_op.drop_column('avatar_url')
        batch_op.drop_column('email')

    # ### end Alembic commands ###
